export objs += display/textmode/dispi_textmode.o

all:
	echo -n "display/textmode/dispi_textmode.o " >> ../../objs.txt
	i586-elf-gcc -c dispi_textmode.c -o dispi_textmode.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra
